services:
  - type: web
    name: laravel-app
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      php artisan migrate --force && \
      php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:S446i6W2xL50xY9EVc460paAwgpaD7CbqmQncYEt8ks=
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: btefqcdii9lfuqunnm5u-mysql.services.clever-cloud.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: btefqcdii9lfuqunnm5u
      - key: DB_USERNAME
        value: utajwenhwaa41bcr
      - key: DB_PASSWORD
        value: VIcpLwdZySmghhsE8Acn
