services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    buildCommand: ""
    startCommand: "sh -c 'php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=3000'"
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:7/c4sS2MJUurbaSvWfUDyaAGkT5Wg+vIjk4BQARO1PY=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: btefqcdii9lfuqunnm5u-mysql.services.clever-cloud.com
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        value: btefqcdii9lfuqunnm5u
      - key: DB_USERNAME
        value: utajwenhwaa41bcr
      - key: DB_PASSWORD
        value: VIcpLwdZySmghhsE8Acn
    autoDeploy: true
    github:
      branch: main

  - type: database
    name: mysql-db
    plan: free
    databaseType: mysql
    databaseVersion: 5.7
    envVars:
      - key: MYSQL_DATABASE
        value: btefqcdii9lfuqunnm5u
      - key: MYSQL_USER
        value: utajwenhwaa41bcr
      - key: MYSQL_PASSWORD
        value: VIcpLwdZySmghhsE8Acn
