services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: ""  # Nous n'en avons pas besoin ici avec Docker
    startCommand: ""  # Pas nécessaire ici, géré par le Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:S446i6W2xL50xY9EVc460paAwgpaD7CbqmQncYEt8ks=  # Si tu l’as déjà générée, ne pas cocher generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: btefqcdii9lfuqunnm5u-mysql.services.clever-cloud.com  # Hôte de la base de données
      - key: DB_PORT
        value: 3306  # Port de la base de données
      - key: DB_DATABASE
        value: btefqcdii9lfuqunnm5u  # Nom de la base de données
      - key: DB_USERNAME
        value: utajwenhwaa41bcr  # Utilisateur de la base de données
      - key: DB_PASSWORD
        value: VIcpLwdZySmghhsE8Acn  # Mot de passe de la base de données
